### ISSUE TITLE
Optional Op-beat support

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#143]
We need Op-beat-support in Gradient. Unfortunately there is a lack of mature/maintained clients for Go, but this looks acceptable, at least on the surface:

https://github.com/roncohen/opbeat-go/blob/master/opbeat.go#L146

I'll add this feature as an option that can be enabled in the config file. In the future we would probably want this to be a plug-in, but the current version of Go can't support that. So for the time being it goes into the core.

**Comment by erikgrinaker** [comment]
I believe this was fixed by publishing errors via NATS. If not, please reopen.
