### ISSUE TITLE
Clean up GQL tests

### ISSUE THREAD

**Issue by atombender** [sanity-io/gradient#191]
- [ ] Use go-spew instead of JSON for the test data
- [ ] Unify ES test data and GQL parses — we want one canonical set of queries
- [ ] Use tests to generate a Markdown document that list all supported syntaxes in one document
- [ ] Find a good, canonical schema (for example: A blog, or an ecommerce system, or a social networking site) that all tests can use, instead of random things like `foo.bar`.

**Comment by erikgrinaker** [comment]
Subsumed into #525
