### ISSUE TITLE
Patch format

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/gradient#196]
I'm sorry for bringing this up this late, but I'm a bit worried about potential issues with the current patch format, relying on the order of properties in JSON-object.

Since the traversal order of the javascript object properties is not very obvious and dependent on (among other) the order _in which properties are added to the object_ (http://www.2ality.com/2015/10/property-traversal-order-es6.html), I'm afraid it could cause confusion and unexpected behavior among developers in the javascript end.

I'd like to proposing using arrays instead, since arrays already has a well defined and clear order.

Here's a couple of alternatives we could consider:
### Alternative 1
```js
const payload = {
  patch: {
    id: 'foo/s4tZYDUyXCCef1YpYu6Js5',
    operations: [ 
      {
        target: 'user.address.zip',
        operation: 'set',
        value: '0551'
      },
      {
        target: 'user.address.zip',
        operation: 'unset'
      }
    ]
  }
}
```

### Alternative 2

```js
const payload = {
  patch: {
    id: 'foo/s4tZYDUyXCCef1YpYu6Js5',
    operations: [ 
      {set: { 'user.address.zip': '0551'}},
      {unset: 'user.address.zip'}
    ]
  }
}
```

Alternative 2 may be more compact, but you may be easily misled to think you can add more keys to each operation, e.g. ```{set: { 'user.address.zip': '0551'}, unset: 'user.address.zip'}``` will take us back to the original format.

Another (general) advantage of arrays over hashes, is that you can give feedback to the developer if you got key clashes. E.g.:
```
{
  "patch": {
    "id": "123",
    "set": {
      "title": "Raiders of the Lost Ark",
    },
    "set": {
      "actors": {
        "_ref": "harrison_ford"
      }
    }
  }
}
```
is impossible to detect (at least in javascript) and give helpful warnings about.

**Comment by atombender** [comment]
Closing until we rearchitect patch system.
