### ISSUE TITLE
Improve error levels/make error handling pluggable

### ISSUE THREAD

**Issue by rexxars** [sanity-io/gradient#245]
We want to hook up some error logging that can report errors to services such as [Opbeat](https://opbeat.com/) and similar. Right now, this is a bit hard because errors are handled in a number of different ways and locations throughout the system. If we could hook into the error reporting such as the logger, we could probably catch most if not all cases.

Also relevant is trying to differentiate the error levels a bit more. For instance, attempting to delete a document that doesn't exist results in an error: `ERROR listening Error deleting listener "_/listeners/T4WjBkNx8tTB7NQy2rB4P9": The mutation(s) failed: The document with the ID "_/listeners/T4WjBkNx8tTB7NQy2rB4P9" was not found`

As does an invalid query: `ERROR server.httpapi.http.[T4WjBkNx8tTB7NQy2rB4IX] Error during listen: Unable to create listener object: The mutation(s) failed: Invalid listener "T4WjBkNx8tTB7NQy2rB4LB": Parse error at position 0: Unable to parse entire expression`

But, actual, "unexpected" errors are also using this level: `ERROR listening Error while parsing mutation notification for "T4WjBkNx8tTB7NQy2rB4UR" in "gradient-test": Malformed document ID: ""`

It would be great if "expected" errors, such as incorrect user-input, would trigger a different level.

**Comment by erikgrinaker** [comment]
Opbeat reporting was handled in ca752919472f51960bc2b9e27e3dee86fba48f8e by publishing errors via NATS. As for error levels, this seems to have improved since this issue was opened - our logs for today show only appropriate `ERROR` messages.
