### ISSUE TITLE
Listener reaper is sometimes ineffective

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#349]
There are signs that large amounts of dead listeners sometimes survive reaping. This is probably caused by some interplay between the query engine and indexer that might be indicative of other interesting bugs. Will not fix atm since the query engine is being totally rewritten, but this must be rechecked once the new query engine is out on staging.

**Comment by rexxars** [comment]
Still seeing a bunch of (very) old listeners documents. Not sure how the reaper functions, but I would expect it to remove old listener documents?

```
  "_id": "_.listeners.0ix0H8SUb2hllg1mcE5sdU",
  "_type": "system.listener",
  "_createdAt": "2017-05-02T12:17:50+02:00",
  "_updatedAt": "2017-05-02T23:45:56+02:00",
```

**Comment by erikgrinaker** [comment]
Listener documents are reaped in the sense that their documents get `deleted = true` (via a delete mutation) when the listener is closed or orphaned. I suppose this is working as indented, and that purging of old documents is a separate concern for a separate job.

@simen @atombender Should we open a new issue for a document purger? Or should the listener reaper hard delete these documents on its own?

**Comment by erikgrinaker** [comment]
Reaper seems to work as intended. I have opened #503 for automated purging of deleted documents.
