### ISSUE TITLE
Query-failure warning-system

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#355]
When queries fail quietly because of certain records, (e.g. passing a field to `path()` and then one record out of a thousand contains an invalid path) there should be a way for the Executor/Evaluator to pass warnings to the end user listing silent failures like this.

If the executor/evaluator encounters a warning while processing a document, processing for that document terminates and it is omitted from results.

Also: Warnings triggered by listener queries should appear in the event stream.

**Comment by erikgrinaker** [comment]
Maybe this should be optional, e.g. a strict mode where warning would cause the query to fail. With important data one might want inconsistencies to fail hard.

**Comment by atombender** [comment]
Conceptually same as #469, let's move this there.
