### ISSUE TITLE
references(id) does not find nested entries 

### ISSUE THREAD

**Issue by thomax** [sanity-io/gradient#379]
Give this data structure:
```
{
  _id: 'xyz',
  article: {
    _ref: '123',
    _type: 'reference'
  }
}
```

`*[references('123')` will return the document with id xyz. However, if the article is nested, e.g. like so:

```
{
  _id: 'xyz',
  content: [
    articles: [
      {
        _ref: '123',
        _type: 'reference'
      }
    ]
  ]
}
```
`*[references('123')` will not return the xyz document.

**Comment by atombender** [comment]
Unable to reproduce. I've created an integration test which works fine on all sorts of structures.

**Comment by thomax** [comment]
Odd, still experience the bug on my end. Here's where:

This query https://81xbpgf3.api.sanity.io/v1/data/query/formakademisk?query=*%5B_id%20%3D%3D%20%22issue_ba0e6c94c6c698f05f56f95c7f405364%22%5D returns a single document (of type issue) which has a nested reference to an article with id article_0f0a178c7ab288e8d8d72d8265fdb40e.

Based on this, I'd expect this query https://81xbpgf3.api.sanity.io/v1/data/query/formakademisk?query=*%5B_id%20%3D%3D%20%22issue_ba0e6c94c6c698f05f56f95c7f405364%22%20%26%26%20references(%22article_0f0a178c7ab288e8d8d72d8265fdb40e%22)%5D to return the same issue, but it doesn't.

I've invited you to the Vega project so you can test and access this data https://sanity.io/manage. Is there anything else I can do to help reproduce this bug?

**Comment by thomax** [comment]
@simen and I just hammered out a test which indicates there's an issue with indexing references. Sometimes they work, sometimes they don't.

**Comment by simen** [comment]
Turns out it was a flaky refs.Is() that had an incomplete list of allowable fields in refs and would reject a map as a non-ref if it happened to come across an unrecognized field name before it saw the _ref.
