### ISSUE TITLE
defined() -> any()?

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#397]
`defined()` is a function that evaluates to true for any property as long as it is assigned. `*[defined(tags)]` returns all documents that have the attribute `tags` set. 

I am afraid `defined` is a misnomer. In the future, when we introduce schemas to the general user, an attribute may be "defined" in the schema but not "assigned" a value in the specific document.

I think we should deprecate defined, and introduce  `any()` as a better named alternative.

**Comment by simen** [comment]
Espen proposed `has()` which I quite like.

**Comment by atombender** [comment]
`any()` and `has()` are both very weak in that their names don't encapsulate precisely what they do. At least with `defined()` you can reason from the name what it does.

**Comment by simen** [comment]
I agree. I have no better suggestion.
