### ISSUE TITLE
Unhelpful error when setting _ref to be non-string

### ISSUE THREAD

**Issue by rexxars** [sanity-io/gradient#401]
Gradient responds with an unhelpful 500 if you send for instance an object to a `_ref` field.
A better error message with a 400 would be great.

**Comment by atombender** [comment]
Possibly outdated issue? I get this:

```
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
Vary: Origin
Date: Wed, 29 Nov 2017 03:42:19 GMT
Content-Length: 168

{"error":{"description":"Not a valid reference: Value of \"_ref\" must be a string: attributes.Attributes{\"_ref\":[]interface {}{1, 2, 3}}","type":"validationError"}}
```

The bad part here is that we get a Go literal, which I've improved.

**Comment by erikgrinaker** [comment]
Confirmed, this gives `400` on `master`. Closing.
