### ISSUE TITLE
Remove CORS (except for local development)

### ISSUE THREAD

**Issue by rexxars** [sanity-io/gradient#404]
Currently there is no way to tell Gradient whether to allow/disallow CORS-requests, or specify which origins. 

For our current usage, we could live with a simple on/off switch, but in the future it would be a nice addition to be able to configure CORS in a fairly fine-grained way.

**Comment by atombender** [comment]
Isn't that something the API gateway should handle?

**Comment by rexxars** [comment]
Which is why I'm fine with either removing the CORS handling altogether or having a simple on/off switch.
We *could* remove the headers on response, of course, but I feel being able to turn it off altogether in gradient would be a better approach.

**Comment by simen** [comment]
In my opinion this should be changed to "Remove CORS support entirely", since Gradient is designed to live behind an api-gateway.

**Comment by atombender** [comment]
👍🏻

**Comment by atombender** [comment]
Though it'd be nice to have CORS for local work (e.g. Rainbow, my development client).

**Comment by erikgrinaker** [comment]
Since the primary use-case is local development, I suggest adding config options to set arbitrary HTTP headers instead. This would allow setting `Access-Control-Allow-Origin: *` for local CORS, and could also be used to set e.g. `Connection: close` and other useful headers.
