### ISSUE TITLE
Validate attribute names

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#406]
GROQ only support attribute names with a-z, A-Z, 0-9, optionally starting with a _. We should always validate that any attributes written to the database is a valid attribute name in GROQ. (We should also add a way to dereference attributes using string values to GROQ, but that should never be required)

**Comment by erikgrinaker** [comment]
Could you please confirm the format? I've begun implementing this, but the unit tests fail because they  use documents with attributes `answer_to_everything` which are not allowed according to the given format.

**Comment by atombender** [comment]
I think something like: `^[a-zA-Z0-9-_]+$`.
