### ISSUE TITLE
Broadcasted commit results incorrect?

### ISSUE THREAD

**Issue by rexxars** [sanity-io/gradient#414]
I thought this was a bit interesting:

If you do two mutations in a transaction, where one of them does a `createIfNotExists` and the other one updates the document with a `patch`, it seems that the broadcasted commit result only includes the create result:

```js
{ commitResult: 
   { namespace: 'gcsaz5mc.playground.DR5C5qH3dUXM',
     id: 's5ouxy-5rw-s8n-ro0-gbiscnhc6',
     mutations: 
      [ { createIfNotExists: 
           { _createdAt: '2017-07-24T12:08:38+02:00',
             _id: 'drafts.ce97a47b-0465-4661-be25-9a4442700216',
             _rev: 's5ouxy-5rw-s8n-ro0-gbiscnhc6',
             _type: 'movie',
             _updatedAt: '2017-07-24T12:08:38+02:00' } },
        { patch: 
           { id: 'drafts.ce97a47b-0465-4661-be25-9a4442700216',
             set: { title: '!' } } } ],
     created: 
      [ { namespace: 'gcsaz5mc.playground.DR5C5qH3dUXM',
          id: 'drafts.ce97a47b-0465-4661-be25-9a4442700216',
          attributes: 
           { _createdAt: '2017-07-24T12:08:38+02:00',
             _id: 'drafts.ce97a47b-0465-4661-be25-9a4442700216',
             _rev: 's5ouxy-5rw-s8n-ro0-gbiscnhc6',
             _type: 'movie',
             _updatedAt: '2017-07-24T12:08:38+02:00' },
          revisionID: 's5ouxy-5rw-s8n-ro0-gbiscnhc6',
          version: 1 } ],
     updated: null,
     deleted: null,
     Timestamp: '2017-07-24T12:08:38.494608+02:00' },
  batch: false }
```

Retrieving the document after the update indicates that the patch is actually performed successfully.

**Comment by atombender** [comment]
I think we coalesce mutations (after all a create + patch is just a create), but it's possible that this can cause confusion, since the mutations don't match what the client put in.

**Comment by rexxars** [comment]
That might be - that makes sense. If so, I would at least expect to see the `title` attribute as part of the document in `created`.

**Comment by simen** [comment]
This has been fixed way back. There was an error in the transaction cache that caused created documents not to reflect subsequent changes.
