### ISSUE TITLE
Mysterious date comparison bug

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#423]
This happened. The documents returned should not correspond to either of the supplied criteria. 

```
*[_type == "product" && (_updatedAt < "2017-03-02T18:38:55+01:00" || (_updatedAt == "2017-03-02T18:38:55+01:00" && _id > "product-2176701"))] |order(_updatedAt desc, _id asc)[0...2]{_id, name, _updatedAt}

Result:
[
  {
    "_id": "product-2091201",
    "_updatedAt": "2017-03-02T18:38:55+01:00",
    "name": "Ch. de Meaux 2013"
  },
  {
    "_id": "product-2095804",
    "_updatedAt": "2017-03-02T18:38:55+01:00",
    "name": "Cold Hand Malus Danica Iseple 2013"
  }
]
```

Searching for the root of the bug, we simplified the query to just constraining for type and `_updatedAt < "2017-03-02T18:38:55+01:00"` which still returned the same documents.

Is there any special handling of dates that hide resolution beneath the json value? Are these values secretly smaller than the provided value? (That should be impossible, no?)

**Comment by atombender** [comment]
Paste the Elasticsearch query?

**Comment by simen** [comment]
Verified as fixed
