### ISSUE TITLE
Reverse the default order of attributes from projections

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#428]
When returning results, Gradient tends to render the final JSON properties in the reverse order they were presented in the query. So `*{_id, title}` yields `[{"title": "Banana", "_id": "the-id"}, ...]`. 

It would be more comfortable if the order was preserved from the projection.

**Comment by atombender** [comment]
JSON is inherently unordered, so I think this is pointless — the order shouldn't matter. More importantly, it would mean we'd have to stop using pure Go maps for `Attributes`, because `map` is unordered, and there'd be additional overhead just to keep the fields sorted.

**Comment by simen** [comment]
Ok
