### ISSUE TITLE
Set charset on content type

### ISSUE THREAD

**Issue by rexxars** [sanity-io/gradient#434]
TL;DR: Send `application/json; charset=utf-8` instead of `application/json` for `content-type`.

While JSON requires data to be UTF-8 encoded, browsers are not clever enough to understand this, so they have a tendency to show the data returned by gradient as iso-8859-1 instead. This is just a minor nitpick since anyone using it would parse the JSON and have it be correct, but seems like a small and easy fix to make debugging slightly easier.

**Comment by thomax** [comment]
Those nitpickings don't get nearly enough love. Good work :)
