### ISSUE TITLE
ES page issues still intermittently a problem

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#435]
The tests that cover whether the query engine correctly handles queries that cross ES page boundaries sometimes (but rarely) fails. When they do it looks like this

```
  1) reference queries in-operator 'in' across ES pages:
      AssertionError: expected [] to deeply equal [ Array(2) ]
      + expected - actual
      -[]
      +[
      +  "newerThanFiller"
      +  "olderThanFiller"
      +]
      
      at assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:293:29)
      at .<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:252:17)
      at ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/overwriteMethod.js:49:33)
      at Context.<anonymous> (test/gradient.test.js:1053:34)
      at next (native)
      at step (test/gradient.test.js:1:191)
      at test/gradient.test.js:1:361
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by simen** [comment]
Turns out this is related to _doc ordering in ES of course not being stable across ES nodes. The fix is never using the _doc ordering for queries that potentially span multiple pages. I.e. _never_ in our case.

**Comment by simen** [comment]
99432a440418f6620a32804464d3a94321a96b69

**Comment by atombender** [comment]
Since ordering by something other than `_doc` is more expensive, I suggest that we don't order by anything (i.e. order is undefined) by default. This would mean that specifying offset will require an order.

**Comment by simen** [comment]
Problem is that the query-executor processes stuff in pages. This introduces random behavior when spread across ES nodes even if the user was not requesting any form of limit or offset.

**Comment by atombender** [comment]
Ugh. [Explanation here](http://moi.vonos.net/bigdata/elasticsearch/).

> However “_doc” is simply a small integer representing the raw “document offset” within a lucene index. Because it is a per-shard value, it does not guarantee consistent ordering of hits in cross-shard searches. And _doc values can change as a result of refresh/merge operations within a shard, making them also variable over time.

However... As an optimization, we could drop a sort if the query limit is less or equal to the iterator batch size, and no sort order has been specified in the query.

Secondly, we should look into using the scroll API again when we're actually scrolling. This is more efficient for large result sets. And `_doc` is consistent within a single scroll cursor.

**Comment by atombender** [comment]
That page also recommends using `_uid` as a sort key when you merely want consistent results:

> The easiest solution is to sort by the “_uid” field. This is a normally-hidden value of form “_type#_id”. When a search specifies a sort-criteria, then each hit has a “sort” member which shows the computed value being sorted on, making the _uid then obvious. Interestingly, fields “_type” and “_id” are actually internally derived from “_uid” rather than being stored explicitly, ie _uid is the “more primitive” field to query. For some reason, sorting on “_id” does not work (at least in version 2.3.5); no error is reported but the “sort” member of each hit in the results is null and the records are not sorted as expected.

**Comment by simen** [comment]
Okay, makes sense. Can implement the _uid-sort, but I don't know how simple it is to know in advance whether a query might lead to paging or not in the execution engine?

**Comment by atombender** [comment]
I believe the ES query source knows whether it will need to fetch more than one page.
