### ISSUE TITLE
ES syncing fails on arrays of arrays

### ISSUE THREAD

**Issue by rexxars** [sanity-io/gradient#479]
The following seems to cause some errors that are not caught properly in the validation step, result in 500-errors:

```js
[
  {
    "patch": {
      "id": "abc123",
      "set": {
        "['Table']": {
          "_type": "table",
          "grid": [
            [
              {"value": 1},
              {"value": 3},
              {"value": 3}
            ],
            [
              {"value": 2},
              {"value": 4},
              {"value": 3}
            ],
          ]
        }
      }
    }
  }
]
```

Error message:
`
 Error 500: Unable to sync transaction result to search store: Failed to sync update of "abc123": Unable to transform document "abc123": Unsupported primitive value of type []interface {}: []interface {}{map[string]interface {}{"value":1}, map[string]interface {}{"value":3}, map[string]interface {}{"value":3}}
`

Seems to make it into the transaction log however, which causes the batch syncer to fail.

**Comment by atombender** [comment]
This is related to array handling in general. #150 is a blocker, as is #374. Arrays of arrays are currently not supported.

**Comment by simen** [comment]
Could we just as a stop-gap measure just not attempt to index arrays that are nested inside arrays. The result will be about exactly what an end user would expect at this point.

**Comment by atombender** [comment]
Yep. I can do that.

**Comment by erikgrinaker** [comment]
Nested arrays are now ignored by the indexer, via #496 cf5a198fe59cc6b7edc82e1f1e79d307c57ffcab
