### ISSUE TITLE
ordering has wrong priority

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#482]
Ordering by multiple fields uses the wrong priority. `order(term1, term2)` orders by term2 first, then term1.

**Comment by atombender** [comment]
Uh, I fixed this? There is another issue, I think we closed it.

**Comment by simen** [comment]
I think this issue is new. I'm guessing the fix for `order(term1) | order(term2)` unfixed `order(term1, term2)`?

**Comment by atombender** [comment]
Ah yes.

**Comment by erikgrinaker** [comment]
The mentioned fix which possibly broke this is d137ddc25a15a88506597e69cb0d6fbfade06121
