### ISSUE TITLE
Mutating a weak ref to a strong ref is possible even if reference target is missin

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#497]
We have reports that it is possible to mutate a weak ref to a strong ref (by deleting `_weak`); the mutation is accepted even when the target does not exist.

**Comment by bjoerge** [comment]
IIRC it was an `unset` patch on `_weak`. I'll double check.

**Comment by bjoerge** [comment]
I'm not able to reproduce this anymore, so closing.
