### ISSUE TITLE
Master broken with ElasticSearch 5.6

### ISSUE THREAD

**Issue by erikgrinaker** [sanity-io/gradient#498]
All queries on `master` fail against ElasticSearch 5.6 with:

```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata access on the _uid field is disallowed"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"gradient_idx-gradient-test-20171128103903lky4rt9yeja2mxmz5xaw9y","node":"yWw-VuI2QyCxDcvqDIW3yQ","reason":{"type":"illegal_argument_exception","reason":"Fielddata access on the _uid field is disallowed"}}]},"status":400}
```

Seems to be caused by recent ES 6.0 work in the [elasticsearch-6.0](/sanity-io/gradient/tree/elasticsearch-6.0) branch that was merged to `master`.

**Comment by erikgrinaker** [comment]
I fixed this locally by reverting 16a003d1b800bdd1c93ed98e61d67f017159bb43. Suppose we need a version check for this then.

**Comment by erikgrinaker** [comment]
Fix committed in e529d7d808bafeb697b8135384f61d5b4b472894, please review.

**Comment by atombender** [comment]
👍  But reading [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html):

> The value of the _id field is also accessible in aggregations or for sorting, but doing so is discouraged as it requires to load a lot of data in memory. In case sorting or aggregating on the _id field is required, it is advised to duplicate the content of the _id field in another field that has doc_values enabled.

I suspect we ought to create an internal ID field with `doc_values` enabled that we can sort on.

**Comment by atombender** [comment]
Pushed as https://github.com/sanity-io/gradient/commit/50a904fcf1f273ccd1eaf263d3df19d3f37036a6.
