### ISSUE TITLE
Limit batch sync iterations by document size not count

### ISSUE THREAD

**Issue by erikgrinaker** [sanity-io/gradient#505]
Batch syncer iterations are currently limited to 10 documents, due to high memory usage when processing large documents (see e.g. #311). However, most documents are small, and could probably be processed in batches of 100.

We should look into whether it is possible to fetch a size-limited batch from the transaction log when syncing, possibly via a windowing function in PostgreSQL.

**Comment by atombender** [comment]
Should be fixed in be48b30. Close if it looks okay!

**Comment by erikgrinaker** [comment]
Nice! But the integration tests fail consistently after this commit due to socket timeouts.

Also, I tried modifying the full sync to use this iterator as well, but it never seemed to complete any syncs, and I got a bunch of connection pool failures. Any idea why?

**Comment by erikgrinaker** [comment]
I believe this has broken more stuff. Trying to import a dataset into an empty Gradient instance runs well for about 9800 documents, but then stalls until Gradient errors out with:

```
ERROR documents.storage.postgresql Transaction begin failed: timeout acquiring connection from pool
```

Restarting Gradient and running the import again (without deleting the old data) makes it hang immediately, with the same error.

**Comment by atombender** [comment]
Probably some iterator is not being closed, causing connections to leak. Will look shortly.

**Comment by atombender** [comment]
Should be good now.

**Comment by erikgrinaker** [comment]
Seems to work great, thanks!

Could you implement this for the full syncer as well please? I tried changing it myself, but got tons of connection timeout errors as well as errors about unexpected namespace names. Faster full syncs will be very useful when migrating indexes for #430 and #374.

**Comment by atombender** [comment]
Pushed!

**Comment by erikgrinaker** [comment]
Thanks, but I got the same error as when I tried implementing this myself, lots of

```
Sync failed: Getting documents from data store failed: Could not start a new transaction: timeout acquiring connection from pool
```

As well as

```
Sync failed: Storing document failed: Unexpected namespace "3do82whm.sanityio.5cm6bbnrxn", expected "lvb7arwo.production.zmBV4GCSHfNr"
```

Before it dies with

```
gradient: Could not start system: Unable to start syncer for data store "default": Unable to start batch syncing of data store "default": Unable to get connection: timeout acquiring connection from pool
```

**Comment by atombender** [comment]
That's weird. I found a bug, which would cause the second error, but not the timeout. Pushed fix, though, try it out.

**Comment by erikgrinaker** [comment]
That seems to have fixed both problems, I've run through a full sync without any issues. Many thanks for implementing this!
