### ISSUE TITLE
!field should also match !defined()

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#529]
We have potentially weird semantics for boolean flags where `!flag` only matches flags that are explicitly set to false. I propose that `!flag` should have the semantics `flag == false || !defined(flag)`, and if you actually want to check for the specific value false, you have to write `flag == false`.

**Comment by erikgrinaker** [comment]
Only if Gradient generally treats `null` as falsey. I think it's important to be consistent here, either it's counts as false everywhere, or it is undefined everywhere.

**Comment by erikgrinaker** [comment]
Let's take a concrete example here, a `towel` with a flag `wet`. If `wet` is `null`, this by definition means that we do not know whether the towel is wet or not - it might be either. Saying `!wet` is `true` implies that it is dry. We don't know this.

**Comment by rexxars** [comment]
As long as you can still query for `wet == false` and only get results where the attribute is _actually_ `false`, I personally think this is acceptable.

**Comment by simen** [comment]
We don't allow null values in Gradient fwiw.

**Comment by erikgrinaker** [comment]
If we allow applying operators on missing attributes, then we implicitly do.

**Comment by simen** [comment]
You're right. `!emptyArray[0]` must also be true if `!falseFlag` is true.

**Comment by atombender** [comment]
We have `nil`, and `!emptyArray[0]` should be `nil`, not `true`. This is the same semantics as all SQL databases (`not null` is `null`). I'm not sure if all our boolean semantics correctly devolves to `null` like this, but we need to be careful here.

**Comment by simen** [comment]
Well, I'm trying to get rid of having to dispense pro-tips like this. Any other suggestions for making these queries easier to get right without thinking?

https://www.sanity.io/docs/schema-types/boolean-type


> *Pro-tip* In GROQ you can handle missing booleans like this *[_type == 'story' && (featured == false || !defined(featured))] which would match stories where featured is false or not defined.

**Comment by erikgrinaker** [comment]
If we actually have `nil`, then `featured in [false, nil]` should work? Or something like Postgres' `COALESCE(featured, false) == false`.

Regardless of syntax, I think it is correct that the user has to decide how to handle `nil` values. It is not obvious that they should be falsey, and in many cases that would be downright wrong.

**Comment by simen** [comment]
I just feel that when I say `!flag` that could be construed as meaning `flag != true` (which I now realize should be our pro-tip since it has the same semantics, but is shorter and more obvious).

**Comment by simen** [comment]
`flag != true` is simple and obvious. I have updated the pro-tip, and am giving up this crusade.
