### ISSUE TITLE
Know when reindexing is necessary

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#530]
Sometimes we make changes in how fields are indexed that are not necessarily backward incompatible. Recently we made a change to how refs are indexed to support the ability to access the component fields of references directly, e.g. `reference._ref == <some string>`. This required refs to be reindexed in order for this syntax to work—in the interim it works inconsistently only for documents that are indexed after this change.

We should have some way to know a version of an index, and a way to quietly reindex everything when this version changes.

**Comment by erikgrinaker** [comment]
Related to #521

**Comment by atombender** [comment]
Reindexing happens automatically when the format version number is incremented. Old indexes are kept until the new indexes are ready.

I'm going to add the version number to the index name as part of #430, which will help with visibility.

**Comment by simen** [comment]
So this is basically how it is, we just forgot to increment the version number as we changed the index format? Close this?

**Comment by atombender** [comment]
I think so. @erikgrinaker?

**Comment by erikgrinaker** [comment]
Sounds good. We'll have to do a full reindex for #430 soon anyway, but I'll make sure to bump the version next time.
