### ISSUE TITLE
Inconsistent behaviour for negativ array slice indices

### ISSUE THREAD

**Issue by erikgrinaker** [sanity-io/gradient#588]
It's not clear how negative indices should work. Consider the following:

```
gradient> [1,2,3,4,5][-2..0]
[]
```

I would expect this to either return `[4,5]`, if negative indices count from the end, or to return `[1]` if negative indices actually count from below 0 (since the 0th element is included in the `..` range).

**Comment by atombender** [comment]
`[-2..0]` means *from index `length - 2` to index `0` inclusive*, which is an empty slice, since this does not include any element. The start index has to be before the end index.

`[-2..-1]` should give you `[4, 5]`.

**Comment by erikgrinaker** [comment]
Indeed. Thanks, I've updated tests and docs.
