### ISSUE TITLE
Race condition with embedded queries with sub-queries

### ISSUE THREAD

**Issue by erikgrinaker** [sanity-io/gradient#589]
Using the movies dataset at https://public.sanity.io/moviesdb.ndjson, the following query sometimes yields an empty result, and sometimes the correct one:

```
{
  "A": *[_type == 'movie' && references(*[_type == 'person' && name match 'Sig*']._id)].title
}
```

Should give:

```
{
  A: [
    WALL·E,
    Avatar,
    WALL·E,
    Avatar,
    Alien,
    Aliens,
    Galaxy Quest
  ]
}
```

But in ~90% of runs gives:

```
{
  A: []
}
```

Probably a race somewhere.

**Comment by simen** [comment]
This seems to be a general problem when queries with sub-queries are embedded in object descriptors. Current workaround is: Don't embed.

**Comment by erikgrinaker** [comment]
This seems to be fixed on `master`, where the result is also free of duplicates.
