### ISSUE TITLE
GQL: Implement first(), returning first element of collection

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#83]
Most GQL queries will result in an array-style result. This is not always desirable, especially for joins. When it is known that a result returns at most one document, or the first document of the collection is the desired document, there should be an easy and obvious way to get at it.

`::/underskog/123` yields and array of documents containing at most the specified document

Some potential syntaxes to get the naked document or null instead:

`<::/underskog/123>`

`first(::/underskog/123)`

The selector may sometimes be quite long, so let's see it with more meat on it:

```
<::underskog/bulletins/123-123> {
  .title, .body, .author,
  "authorImage": <::underskog/assets/*[._id == ^.author.imageAssetId]>
}
```

```
first(::underskog/bulletins/123-123) {
  .title, .body, .author,
  "authorImage": first(::underskog/assets/*[._id == ^.author.imageAssetId])
}
```

**Comment by atombender** [comment]
We now have `[0]`.
